# Generated by Django 5.0.6 on 2024-06-26 11:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='saludo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Creado', models.DateTimeField(auto_now_add=True)),
                ('Modificado', models.DateTimeField(auto_now=True)),
                ('Status', models.BooleanField(default=True)),
                ('pk_publica', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('Codigo', models.CharField(blank=True, max_length=60, null=True)),
                ('mensaje', models.CharField(max_length=300)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
